import pygame
import typing

ColorValue: typing.TypeAlias = typing.Union[typing.Tuple[int, int, int], typing.Sequence, pygame.Color]

@typing.runtime_checkable
class PenBase(typing.Protocol):
    position: typing.Tuple[float, float]
    heading: float
    color: pygame.Color
    size: int
    figure: typing.Optional[pygame.Surface]
    path: typing.List[typing.List[typing.Tuple[float, float]]]

    def __init__(
        self, 
        position: typing.Tuple[float, float], 
        heading: float, 
        color: ColorValue, 
        size: int, 
        figure: typing.Optional[pygame.Surface] = None
    ) -> None: ...

    def set_size(self, size: int = 2) -> None: ...
    def set_speed(self, speed: float = 50) -> None: ...
    @typing.overload
    def set_color(self, r: int, g: int, b: int) -> None: ...
    @typing.overload
    def set_color(self, color: ColorValue) -> None: ...
    def set_color(self, *args: typing.Any) -> None: ...
    def hide(self) -> None: ...
    def show(self) -> None: ...
    def penup(self) -> None: ...
    def pendown(self) -> None: ...

@typing.runtime_checkable
class NavigatorBase(typing.Protocol):
    heading: float
    speed: float

    def __init__(
        self, 
        position: typing.Tuple[float, float], 
        heading: float = 0.0, 
        speed: float = 0.0
    ) -> None: ...
    @property
    def position(self) -> typing.Tuple[float, float]: ...
    # Minimal methods
    def forward(self, distance: float) -> None: ...
    @typing.overload
    def goto(self, x: float, y: float) -> None: ...
    @typing.overload
    def goto(self, pos: typing.Tuple[float, float]) -> None: ...
    def goto(self, x: typing.Union[typing.Tuple[float, float], float], y: typing.Optional[float] = None) -> None: ...
    @typing.overload
    def teleport(self, x: float, y: float) -> None: ...
    @typing.overload
    def teleport(self, pos: typing.Tuple[float, float]) -> None: ...
    def teleport(self, x: typing.Union[typing.Tuple[float, float], float], y: typing.Optional[float] = None) -> None: ...
    def right(self, angle: float) -> None: ...
    def left(self, angle: float) -> None: ...

@typing.runtime_checkable
class TurtleBase(typing.Protocol):
    screen: typing.ClassVar = None

    heading: float
    speed: float
    color: pygame.Color
    size: int
    figure: typing.Optional[pygame.Surface]
    path: typing.List[typing.List[typing.Tuple[float, float]]]

    def __init__(
        self, 
        figure: typing.Optional[pygame.Surface] = None, 
        undo_stack: int = 5, 
        visible: bool = True
    ) -> None: ...
    @property
    def position(self) -> typing.Tuple[float, float]: ...
    def reset(self) -> None: ...
    def set_figure(self, surface: pygame.Surface) -> None: ...
    def clear(self) -> None: ...
    def undo(self) -> None: ...
    def redo(self) -> None: ...
    def custom_command(
        self, 
        id_or_func: typing.Union[typing.Callable, int], 
        *args: typing.Any
    ) -> None: ...
    def commit(self) -> None: ...